### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by EndrII** [DeadAirRT/DeadAirDynamicWars#3]
Is it possible to add support for several languages to this mod?
or need to fork this mod.

**Comment by DeadAirRT** [comment]
I could rewrite the news segments to be t file references but I would need someone to translate to different language. If that's something that people want, I don't mind putting in the work. I didn't think about it tbh when I initially wrote the script.

**Comment by EndrII** [comment]
good idea, I could help with the translation into Russian.
But what about the dialogs with manager of station, will you also take them out into separate files?

**Comment by DeadAirRT** [comment]
It will basically turn all strings into t file entries. At least that is the plan.

**Comment by DeadAirRT** [comment]
Do you think you could help me translate tatertrader as well?

https://github.com/DeadAirRT/TaterTrader/tree/master/t

I'm going to transition dynamic war to T-files tomorrow.

**Comment by EndrII** [comment]
yes ) i am help you.

**Comment by EndrII** [comment]
What is the id of Russian localization?

**Comment by DeadAirRT** [comment]
It should have the country code in the file name. I'll try to get it all merged in, thank you!
