### ISSUE TITLE
Russian locale

### ISSUE THREAD

**Issue by EndrII** [DeadAirRT/DeadAirDynamicWars#6]
Russian text does not work in version 1.22
If this is due to developers problems. write in this thread when they are resolved.

**Comment by DeadAirRT** [comment]
did it work previously for you and break in beta?

**Comment by EndrII** [comment]
x4 3.10 mod steam version
Russian text did not appear at all, in none of the versions. All in English.

**Comment by EndrII** [comment]
thanks, I don’t know what you did, but now it works
))

**Comment by DeadAirRT** [comment]
So there is a bit of an issue with steam when it updates. Usually closing the game then reopening should fix it.
