### ISSUE TITLE
[possible Bug] no list of factions relations and their number of ships  

### ISSUE THREAD

**Issue by morgenrot68** [DeadAirRT/DeadAirDynamicWars#8]
Hello,
unfortunately the entry 'faction information ' (esc - extension options) does not exist. Therefore I cannot show a list of the faction relation or the ship list.
The MOD 'SN_MOD_Support_ Api' (V1.80) is installed.

**Comment by morgenrot68** [comment]
Problem solved !
Can be closed.
I didn't know that there has to be a Load/Save/Load savegame cycle for the 'Sir Nukes Mod Support Api' to work properly after a new Mod installation.

**Comment by DeadAirRT** [comment]
Glad to hear it got resolved, sorry for the very long absence.
