### ISSUE TITLE
[Bug] wrong calculation of the military and economic strength

### ISSUE THREAD

**Issue by morgenrot68** [DeadAirRT/DeadAirDynamicWars#9]
Hello,

The number of ships at military and economic strength is completely wrong. Unfortunately only the ships that are not docked are counted. All ships should be counted and listed.
I noticed this because I didn't have any Player s-ships and m-ships in the list. But I have many. The ships were docked. As soon as I started the ships, they also appeared in the list.

I can't tell yet if the AI ships are also calculated incorrectly. I have not tested that yet. But I assume that it is so. The calculation is probably the same.

**Comment by DeadAirRT** [comment]
Thanks for the report, I'll try to track down a solution.

**Comment by DeadAirRT** [comment]
Fixed in 1.35 for the display portion of the script. Due to performance impact, leaving the calculation the same in the faction selection weighting (non-player visible).
